name: Build lpac x86_64 MBIM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Official lpac Source
        uses: actions/checkout@v4
        with:
          repository: estkme-group/lpac
          submodules: recursive
          path: lpac-src

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c

      - name: Configure and Compile with CMake
        run: |
          cd lpac-src
          mkdir build && cd build
          
          # Запускаем штатную конфигурацию Android NDK x86_64.
          # Флаг -DINTERFACE_PCSC=OFF принудительно гасит требования к PCSC на уровне CMake.
          cmake -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=x86_64 \
                -DANDROID_PLATFORM=android-29 \
                -DAPP_STL=c++_static \
                -DLPA_HTTP=curl \
                -DINTERFACE_MBIM=ON \
                -DINTERFACE_PCSC=OFF \
                -DINTERFACE_AT=OFF \
                ..
                
          # Запускаем сборку проекта
          make -j4

      - name: Upload Finished Binary
        uses: actions/upload-artifact@v4
        with:
          name: lpac-android-x86_64-mbim
          path: lpac-src/build/lpac
          
